version: "3"  # optional since v1.27.
services:
  node:
    container_name: docker-node
    build:
      context: ./
      dockerfile: Dockerfile
      # volumes:
      # - ./:/code
    # stdin_open: true
    # tty: true
    ports:
      - 80:3000
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
#     volumes:
#       - mongodb:/data/db
# volumes:
#   mongodb: