version: "3"  # optional since v1.27.
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: ala/app:latest
    stdin_open: true
    tty: true
    ports:
      - "80:8080"
    volumes:
      - ./app:/app
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ala/api:latest
      # volumes:
      # - ./:/code
    # stdin_open: true
    # tty: true
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ~/apps/mongo:/data/db
