# FROM jboss/keycloak:7.0.1
FROM jboss/keycloak:11.0.1
# ENV KEYCLOAK_WELCOME_THEME=mac
# COPY --chown=jboss:1000 ./config/standalone.xml /opt/jboss/keycloak/standalone/configuration/
# COPY --chown=jboss:1000 ./config/profile.properties /opt/jboss/keycloak/standalone/configuration/
# COPY ./config/my-script.jar /opt/jboss/keycloak/standalone/deployments/
# COPY ./config/mongo-init.js /docker-entrypoint-initdb.d/
