version: '3' # optional since v1.27.
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - '80:8080'
    volumes:
      - .:/app
  keycloak:
    # restart: always
    image: 'jboss/keycloak:11.0.1'
    # build: ./keycloak
    container_name: 'spacer-sso'
    hostname: 'sso'
    environment:
      # KEYCLOAK_WELCOME_THEME: mac
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8008:8443
      - 466:465
    volumes:
      - ./ssl:/etc/x509/https
      # - ./keycloak/mac:/opt/jboss/keycloak/themes/mac
      # - ./keycloak/keycloak:/opt/jboss/keycloak/themes/keycloak
    depends_on:
      - postgres
    networks:
      - keycloak-net
networks:
  keycloak-net:
