version: "3"  # optional since v1.27.
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/api